# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: QT-application

on:
  push:
    branches:
       - '**'        # matches every branch
  pull_request:
    branches:
       - '**'        # matches every branch

env:
  PYTHONPATH: ./src

jobs:
  flake8:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. black defaults to 88 characters
          flake8 . --exclude src/ui/*, --count --exit-zero --max-complexity=18 --max-line-length=120 --statistics